### ISSUE TITLE
Créer un fichier requirements.txt

### ISSUE THREAD

**Issue by MaitreMenard** [ul-gaul/Avionique_Software#24]
Il serait très utile de créer un fichier requirements.txt pour que pip puisse installer en une seule commande toutes les dépendances du projet, ce qui faciliterait la vie des nouveaux contributeurs.

pip install -r requirements.txt

https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by PharaOFred** [comment]
Setter une version X de chaque librairie pour le fichier requirements.txt
