### ISSUE TITLE
Problème d'affichage de PyQTGraph sur linux

### ISSUE THREAD

**Issue by MaitreMenard** [ul-gaul/Avionique_Software#39]
Les graphiques réalisés avec PyQtGrah (altitude et position relative au camp de base) ne fonctionnent pas sur Linux. Les axes, les titres et la ligne de 10000 pieds (dans le cas de l'altitude) s'affichent correctement à l'ouverture, mais les graphiques ne s'updatent pas lors de l'acquisition.

**Comment by konoufo** [comment]
Après test, ceci est probablement lié a l'overhead causé par le rendu du modele de fusée #25 .  Résoudre ce dernier devrait éliminer le présent problème.

**Comment by MaitreMenard** [comment]
Ce bug était probablement causé par un problème de concurrence qui survenait puisqu'on updatait les composants de l'interface depuis un thread distinct du thread principal de QT. En utilisant un `QTimer` pour scheduler des updates périodiques sur le thread principal de QT, les graphiques s'affichent correctement à nouveau.
